---
  # ---------------------------------------------------
  # configuration des packages necessaires pour Linux
  # ---------------------------------------------------

#  - name: Installation des RPMs libselinux et libselinux-python
#    yum: name={{ item }} state=present
#    with_items:
#      - libselinux
#      - libselinux-python
#      - libselinux-utils
#
#   - name: Copie du fichier repository public-yum si absent
#     copy:
#       src="public-yum-ol{{ ansible_distribution_major_version }}.repo"
#       dest="/etc/yum.repos.d/public-yum-ol{{ ansible_distribution_major_version }}.repo"
#     tags: publicyumrepo
#
#   - name: Copie de la clé GPG
#     # sans cette clé, la commande YUM retourne l'erreur suivante :
#     # Couldn't open file /etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
#     copy: src=RPM-GPG-KEY-oracle dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
#     tags: rpmgpgkey

  # ---------------------------------------------------
  # maintenant on install les rpms
  # ---------------------------------------------------
   - name: YUM - installation des packages nécessaires
     yum:  name={{ item }} state=latest disable_gpg_check=yes
     with_items: "{{ linux_packages }}"


   - name: Configuration du mode panic sur perte du /
     shell: free_form="tune2fs -e panic `df -P / |tail -1 | awk '{print $1}'`"

  # ---------------------------------------------------
  # configuration du serveur NTPD
  # ---------------------------------------------------
   - name: Modification de la configuration NTP configuration (ajout du flag -x)
     lineinfile: dest="/etc/sysconfig/ntpd"
              regexp='^OPTIONS='
              line='OPTIONS="-x -u ntp:ntp -p /var/run/ntpd.pid -g"'
              state=present
              create=yes

   - name: restart ntpd
     service: name=ntpd  state=started  enabled=yes

  # ---------------------------------------------------
  # configuration Linux : Selinux
  # ---------------------------------------------------
   - name: Disactiver Selinux (de façon permanente)
     selinux: state=disabled
     register: selinux

   - name: Disactiver Selinux (runtime)
     shell: setenforce 0
     ignore_errors: true

  # ---------------------------------------------------
  # configuration Linux : les services
  # ---------------------------------------------------
   - name: arrêter et désactiver les services inutils
     with_items: "{{ linux_services }}"
     service: name={{ item }}  state=stopped  enabled=no
     tags: linuxservices
     ignore_errors: true

  #------------------------------------------------------------------------------------
  # configuration Linux : Paramètres du kernel
  #------------------------------------------------------------------------------------
   - name: Linux - Ajustement des paramètres du Kernel dans /etc/sysctl.conf
     sysctl:
       name={{ item.name }} value={{ item.value }}
       state=present reload=yes ignoreerrors=yes sysctl_set=yes
     with_items: "{{ oracle_sysconfig }}"
     tags: sysctl.conf 

   - name: Configuration PAM
     lineinfile: dest=/etc/pam.d/login state=present line="session required pam_limits.so"
     tags: pamconfig

   - name: Linux - Ajustement des limits pour Oracle dans /etc/security/limits.conf
     lineinfile: dest=/etc/security/limits.conf create=yes state=present line={{ item }}
     with_items: "{{ oracle_seclimits }}"
     tags: seclimit

   - name: Linux 6 - Configuration du mode 3 comme mode de démarrage par défaut
     replace: dest=/etc/inittab regexp='id:5:initdefault:' replace='id:3:initdefault:'
     when: ansible_distribution_major_version == '6'

   - name: Linux 7/8 - Configuration du mode 3 comme mode de démarrage par défaut
     shell: systemctl set-default multi-user.target
     when: ansible_distribution_major_version >= '7'

   - name: BASH - ajout de ignore-case pour autocompletion avec TAB
     lineinfile: dest=/etc/inputrc line="set completion-ignore-case On" create=yes state=present

   - name: BASH - copie du fichier des alias
     copy:
       src="99_alias_bash.sh"
       dest="/etc/profile.d/99_alias_bash.sh"
       owner=root
       group=root
       mode=0644
     tags: bash_alias
