---
  # --------------------------------------------------- 
  # configuration Linux : Utilisateurs et groupes
  # ---------------------------------------------------
 
  - name: Création des groupes
    group: name={{ item.group }} gid={{ item.gid }} state=present
    with_items: "{{ oracle_groups }}"
    tags: group

  - name: Création du compte Oracle
    user: 
      name={{ item.username }}  group={{ item.primgroup }} 
      groups={{ item.othergroups }} uid={{ item.uid }} 
      generate_ssh_key=yes append=yes state=present password={{ item.passwd }}
    with_items: "{{ oracle_users }}"
    tags: user

  - name: Création du compte grid
    user: 
      name={{ item.username }}  group={{ item.primgroup }} 
      groups={{ item.othergroups }} uid={{ item.uid }} 
      generate_ssh_key=yes append=yes state=present password={{ item.passwd }}
    with_items: "{{ grid_users }}"
    when: role_separation
    tags: user

  # --------------------------------------------------- 
  # configuration Linux : config oracle pour logrotate
  # ---------------------------------------------------
  - name: Gestion des logs Oracle - copy du fichier de configuration pour logrotate
    copy: src=logrotate_oracle dest=/etc/logrotate.d/oracle mode=644 owner=root group=root
    tags: logrotate

