---

  # ---------------------------------------------------
  # Fichier pour les paramètres communs à toutes les versions Linux
  # ---------------------------------------------------

  # si le serveur n'pas d'accès internet, mettre la variable suivante à FALSE
  # dans ce cas, les rpm seront installée depuis le serveur Ansible
  internet_connection: true
  # faire une configuration securisée du system d'exploitation
  secure_configuration: false
  # Ajouter le dépôt epel : true ou false
  # Pour pouvoir installer des packets comme rlwrap, htop, multitail, ...
  configure_epel_repo: true


  #----------------------------------------------------------------------
  # paramètres du noyeau pour une installation Oracle
  #----------------------------------------------------------------------
  oracle_sysconfig:
      - { name: fs.aio-max-nr, value: 1048576 }
      - { name: fs.file-max, value: 6815744 }
      - { name: kernel.sem, value: "250 32000 100 128" }
      - { name: kernel.shmall, value: "{{ ((0.4 * (ansible_memtotal_mb+1))*1024*1024)|round|int  }}" }
      - { name: kernel.shmmax, value: "{{ ((0.5 * (ansible_memtotal_mb+1))*1024*1024)|round|int  }}" }
      - { name: kernel.shmmni, value: 4096 }
      - { name: net.core.rmem_default, value: 262144 }
      - { name: net.core.rmem_max, value: 4194304 }
      - { name: net.core.wmem_default, value: 262144 }
      - { name: net.core.wmem_max, value: 1048576 }
      - { name: net.ipv4.ip_local_port_range, value: "9000 65500" }
#      - { name: vm.nr_hugepages, value: "{{ (((percent_hugepages/100) * ansible_memtotal_mb)/2)|round|int  }}" }

  #----------------------------------------------------------------------
  # paramètres security limits pour une installation Oracle
  #----------------------------------------------------------------------
  oracle_seclimits:
      - "* soft nproc 2047"
      - "* hard nproc 16384"
      - "* soft nofile 1024"
      - "* hard nofile 65536"
      - "* soft memlock {{ ((0.9 * ansible_memtotal_mb)*1024*1024)|round|int }}"
      - "* hard memlock {{ ((0.9 * ansible_memtotal_mb)*1024*1024)|round|int }}"
      - "* soft stack 10240"
      - "* hard stack 32768"
      - "* soft core unlimited"
      - "* hard core unlimited"

  #----------------------------------------------------------------------
  # services Linux à désactiver :
  #----------------------------------------------------------------------
  linux_services:
      - avahi-daemon
      - bluetooth
      - chronyd
      - cups
      - firewalld
      - firstboot
      - gpm
      - hidd
      - hplip
      - ip6tables
      - iptables
      - isdn
      - mcstrans
      - mdmonitor
      - NetworkManager
      - postfix
      - restorecond
      - rhnsd
      - sendmail
      - setroubleshoot
      - smartd
      - yum-updatesd

  #---------------------------------------------------------------------
  # pramètres de configuation sécurisée :
  #---------------------------------------------------------------------
  linux_secure_config:
      - { name: net.ipv4.conf.all.accept_redirects, value: 0 }
      - { name: net.ipv4.conf.all.accept_source_route, value: 0 }
      - { name: net.ipv4.conf.all.log_martians, value: 1 }
      - { name: net.ipv4.conf.all.secure_redirects, value: 0 }
      - { name: net.ipv4.conf.default.accept_redirects, value: 0 }
      - { name: net.ipv4.conf.default.accept_source_route, value: 0 }
      - { name: net.ipv4.conf.default.log_martians, value: 1 }
      - { name: net.ipv4.conf.default.secure_redirects, value: 0 }
      - { name: net.ipv4.icmp_echo_ignore_broadcasts, value: 1 }
      - { name: net.ipv4.icmp_ignore_bogus_error_responses, value: 1 }
      - { name: net.ipv4.ip_forward, value: 0 }
      - { name: net.ipv6.conf.all.accept_ra, value: 0 }
      - { name: net.ipv6.conf.all.accept_redirects, value: 0 }
      - { name: net.ipv6.conf.all.accept_source_route, value: 0 }
      - { name: net.ipv6.conf.default.accept_ra, value: 0 }
      - { name: net.ipv6.conf.default.accept_redirects, value: 0 }
      - { name: net.ipv6.conf.default.accept_source_route, value: 0 }

