#--------------------------------------------------------------------
# paramètres commun
# dans cette section ne rien modifier sauf si besoin
#--------------------------------------------------------------------

role_separation: true
grid_install_user: "{% if role_separation==true %}{{ grid_user }}{% else %}{{ oracle_user }}{% endif %}"

oracle_users:         # Passwd :Oracle123
  - { username: oracle, uid: 1001, primgroup: oinstall, othergroups: "dba,asmdba,backupdba,dgdba,kmdba,oper,racdba", passwd: "$6$0xHoAXXF$K75HKb64Hcb/CEcr3YEj2LGERi/U2moJgsCK.ztGxLsKoaXc4UBiNZPL0hlxB5ng6GL.gyipfQOOXplzcdgvD0" }

grid_users:
  - { username: grid, uid: 1002, primgroup: oinstall, othergroups: "asmadmin,asmdba,asmoper,dba,racdba", passwd: "$6$0xHoAXXF$K75HKb64Hcb/CEcr3YEj2LGERi/U2moJgsCK.ztGxLsKoaXc4UBiNZPL0hlxB5ng6GL.gyipfQOOXplzcdgvD0" }

oracle_group: "oinstall"
dba_group: "dba"
oinstall_group: "oinstall"
oper_group: "oper"
backupdba_group: "backupdba"
dgdba_group: "dgdba"
kmdba_group: "kmdba"
asmdba_group: "asmdba"
asmoper_group: "asmoper"
asmadmin_group: "asmadmin"
racdba_group: "racdba"

oracle_groups:
  - { group: oinstall, gid: 1001}
  - { group: dba, gid: 1002 }
  - { group: asmadmin, gid: 1003 }
  - { group: asmdba, gid: 1004 }
  - { group: asmoper, gid: 1005 }
  - { group: backupdba, gid: 1006 }
  - { group: dgdba, gid: 1007 }
  - { group: kmdba, gid: 1009 }
  - { group: oper, gid: 1009 }
  - { group: racdba, gid: 1010 }

oracle_stage: "/u01/stage"

# u01_free_space 4 Go pour l'install et 4 Go pour transfert et decompression des zip
u01_free_space_gb: 8
tmp_free_space_gb: 1
etc_free_spage_gb: 1
var_free_spage_gb: 1

#--------------------------------------------------------------------
# paramètres d'installation grid infra
#--------------------------------------------------------------------
gi_user: "grid"
gi_response_file: "install_gi_{{ gi_version }}.rsp"

#--------------------------------------------------------------------
# paramètres d'installation des binaires de la base
#--------------------------------------------------------------------
db_user: "oracle"

db_edition: "EE"
db_response_file: "install_db_{{ db_version }}_{{ db_edition }}.rsp"

