---
  #-------------------------------------------
  # configuration squid
  #-------------------------------------------

  - name: copie du fichier de configuration squid.conf 
    template: src=squid.conf.j2 dest=/etc/squid3/squid.conf owner=root group=root mode=0644
    # copy: src=squid.conf dest=/etc/squid3 owner=root group=root mode=0644

  - name: redémarrage du service squid3
    service: name=squid3 state=restarted

